spring:
  application:
    name: planmate
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/plan_mate?useSSL=false&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password:
    hikari:
      connection-timeout: 9000
      idle-timeout: 150000
      max-lifetime: 300000
      maximum-pool-size: 5
      minimum-idle: 5
      data-source-properties:
        v$session.program: SampleDev
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
